### ISSUE TITLE
line graph in README.md

### ISSUE THREAD

**Issue by tamaroning** [Multi-V-VM/MVVM#19]
Hello, could you tell me about what "2^N" and "Func" mean in the line graph in README.md?

![image](https://github.com/user-attachments/assets/60a77083-eebf-496e-b868-21df38a7e34d)

**Comment by victoryang00** [comment]
it means how much frequency we try to skip codegen checkpoint for a loop. 2^1 means every 2 loops has a checkpoint.

**Comment by tamaroning** [comment]
Understand. Thank you!
